server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  smtp:
    host: localhost
    port: 1025
    from: test@test.com
    pwd: "$PWD"
    templates_dir: ./app/email/templates
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
