server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s
auth:
  jwt:
    secret: supersecret
    expire: 3600s
data:
  database:
    driver: postgres
    url: localhost:5432
    user: admin
    password: admin
    dbname: test
